<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import MobileShell from '../components/MobileShell.vue';
import { getStoredUser } from '../services/auth';
import { acceptClientInvitation, fetchDriverClients, inviteClient, leaveClientFleet, rejectClientInvitation, searchClients, toggleClientRequests } from '../services/driverClients';

const user=ref(null),data=ref(null),loading=ref(true),error=ref(null),query=ref(''),results=ref(null),searching=ref(false),acting=ref(null),filter=ref('todos');
let timer=null,searchId=0;
const memberships=computed(()=>data.value?.active_memberships||[]);
const clientName=(item)=>item?.fleet?.owner?.full_name||[item?.fleet?.owner?.name,item?.fleet?.owner?.last_name].filter(Boolean).join(' ')||'Cliente de confianza';
const clientAvatar=(item)=>item?.fleet?.owner?.avatar_url;
async function load(){loading.value=true;error.value=null;try{data.value=await fetchDriverClients(filter.value)}catch(e){error.value=e.message}finally{loading.value=false}}
function changeFilter(value){filter.value=value;load()}
function onSearch(){clearTimeout(timer);const term=query.value.trim();if(term.length<2){results.value=null;return}timer=setTimeout(async()=>{const id=++searchId;searching.value=true;try{const response=await searchClients(term);if(id===searchId)results.value=response.clients}catch(e){if(id===searchId)error.value=e.message}finally{if(id===searchId)searching.value=false}},300)}
async function action(key,fn){acting.value=key;error.value=null;try{await fn();await load()}catch(e){error.value=e.message}finally{acting.value=null}}
async function send(client){await action(`client-${client.user_id}`,()=>inviteClient(client.user_id));client.status='pending'}
async function shareInvite(){const code=data.value?.invite_code;if(!code)return;const text=`Soy conductor en Arka01. Agrégame a tu flota de confianza con mi código ${code}.`;if(navigator.share)await navigator.share({title:'Agregar conductor Arka01',text});else await navigator.clipboard?.writeText(text)}
onMounted(async()=>{user.value=await getStoredUser();await load()});onBeforeUnmount(()=>clearTimeout(timer));
</script>

<template><MobileShell v-if="user" role="conductor" :user-name="user.name"><main class="mobile-page clients-page">
    <header><p class="mobile-eyebrow">Tu red de confianza</p><h1 class="mobile-title">Mis clientes</h1><p class="intro">Acepta invitaciones, administra quién puede enviarte solicitudes y busca clientes existentes.</p></header>
    <p v-if="error" class="mobile-alert">{{ error }}</p>
    <section v-if="data" class="summary mobile-card"><div><small>Plan {{ data.plan_name }}</small><strong>{{ data.active_membership_stats?.total || 0 }} / {{ data.max_clients ?? '∞' }}</strong><span>clientes activos</span></div><button v-if="data.invite_code" @click="shareInvite">Compartir mi código</button></section>
    <section class="search mobile-card"><p class="mobile-eyebrow">Agregar cliente</p><h2>Buscar por nombre o código</h2><input v-model="query" class="mobile-input" placeholder="Nombre, usuario o código" @input="onSearch"><small v-if="searching">Buscando…</small><div v-if="results" class="search-results"><p v-if="!results.length" class="empty">No encontramos clientes.</p><article v-for="client in results" :key="client.user_id"><span class="avatar"><img v-if="client.avatar_url" :src="client.avatar_url"><b v-else>{{ client.name?.[0] }}</b></span><div><strong>{{ client.name }}</strong><small>{{ client.username ? '@'+client.username : client.city || 'Cliente Arka01' }}<template v-if="client.average_rating"> · ★ {{ client.average_rating }}</template></small></div><button v-if="client.status==='not_invited'" :disabled="acting===`client-${client.user_id}`" @click="send(client)">Invitar</button><em v-else>{{ client.status==='member'?'Ya es cliente':client.status==='cooperative_locked'?'Vinculado a cooperativa':'Pendiente' }}</em></article></div></section>
    <section v-if="data?.pending_invitations?.length"><div class="section-title"><p class="mobile-eyebrow">Pendientes</p><h2>Invitaciones recibidas</h2></div><article v-for="inv in data.pending_invitations" :key="inv.id" class="client-card mobile-card"><div><strong>{{ inv.fleet?.owner?.full_name || inv.fleet?.owner?.name || 'Cliente' }}</strong><small>Te invita a {{ inv.fleet?.name || 'su flota' }}</small><span v-if="inv.client_rating">★ {{ inv.client_rating }} · {{ inv.driver_count || 0 }} conductores</span></div><div class="actions"><button class="accept" @click="action(`accept-${inv.id}`,()=>acceptClientInvitation(inv.id))">Aceptar</button><button class="reject" @click="action(`reject-${inv.id}`,()=>rejectClientInvitation(inv.id))">Rechazar</button></div></article></section>
    <section><div class="section-title"><p class="mobile-eyebrow">Cartera activa</p><h2>Clientes de confianza</h2></div><div class="filters"><button v-for="chip in [{v:'todos',l:'Todos'},{v:'nuevos',l:'Nuevos'},{v:'con_carreras',l:'Con carreras'},{v:'sin_carreras',l:'Sin carreras'}]" :key="chip.v" :class="{active:filter===chip.v}" @click="changeFilter(chip.v)">{{ chip.l }}</button></div><p v-if="loading" class="empty">Cargando clientes…</p><p v-else-if="!memberships.length" class="empty mobile-card">Todavía no tienes clientes en esta categoría.</p><article v-for="member in memberships" :key="member.id" class="client-card mobile-card"><span class="avatar large"><img v-if="clientAvatar(member)" :src="clientAvatar(member)"><b v-else>{{ clientName(member)[0] }}</b></span><div class="client-copy"><strong>{{ clientName(member) }}</strong><small>{{ member.fleet?.name }} · {{ member.rides_together_count || 0 }} carreras</small><span>{{ member.client_rating ? `★ ${member.client_rating} (${member.client_review_count})` : 'Sin calificaciones' }}<template v-if="member.mutual_clients_count"> · {{ member.mutual_clients_count }} en común</template></span></div><div class="member-actions"><button @click="action(`toggle-${member.id}`,()=>toggleClientRequests(member.id))">{{ member.requests_disabled?'Activar solicitudes':'Pausar solicitudes' }}</button><button class="danger" @click="action(`leave-${member.id}`,()=>leaveClientFleet(member.id))">Salir</button></div></article></section>
</main></MobileShell></template>

<style scoped>.clients-page{display:grid;gap:1.1rem}.intro{margin:.45rem 0 0;color:var(--arka-muted);font-size:.82rem;line-height:1.45}.summary{padding:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem}.summary div{display:grid}.summary small,.summary span{color:var(--arka-muted);font-size:.7rem}.summary strong{font-size:1.35rem}.summary button,.search article button,.actions button,.member-actions button{border:0;border-radius:.75rem;padding:.6rem .75rem;background:var(--arka-primary);color:#fff;font-size:.72rem;font-weight:800}.search{padding:1rem;display:grid;gap:.65rem}.search h2,.section-title h2{margin:.18rem 0 0;font-size:1.05rem}.search>small,.empty{color:var(--arka-muted);font-size:.78rem}.search-results{display:grid}.search article{padding:.7rem 0;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:.65rem;border-top:1px solid var(--arka-border)}.search article div{min-width:0;display:grid}.search article small,.client-card small,.client-card span{color:var(--arka-muted);font-size:.7rem}.search article em{color:var(--arka-primary);font-size:.68rem;font-style:normal}.avatar{width:2.35rem;height:2.35rem;display:grid;place-items:center;overflow:hidden;border-radius:50%;background:var(--arka-primary-soft);color:var(--arka-primary)}.avatar.large{width:3rem;height:3rem}.avatar img{width:100%;height:100%;object-fit:cover}.client-card{padding:1rem;display:grid;grid-template-columns:auto minmax(0,1fr);gap:.75rem;margin-top:.65rem}.client-card>div:first-child,.client-copy{min-width:0;display:grid;gap:.18rem}.actions,.member-actions{grid-column:1/-1;display:flex;gap:.5rem}.actions button,.member-actions button{flex:1}.actions .reject,.member-actions .danger{border:1px solid color-mix(in srgb,var(--arka-danger) 40%,transparent);background:transparent;color:var(--arka-danger)}.filters{display:flex;gap:.4rem;overflow-x:auto;padding:.65rem 0}.filters button{flex:none;border:1px solid var(--arka-border);border-radius:999px;padding:.5rem .7rem;background:var(--arka-card);color:var(--arka-muted);font-size:.7rem}.filters button.active{border-color:var(--arka-primary);background:var(--arka-primary-soft);color:var(--arka-primary)}.empty.mobile-card{padding:1rem}.section-title{padding:0 .2rem}</style>
