<script setup>
import { onMounted, ref } from 'vue';
import MobileShell from '../components/MobileShell.vue';
import { getStoredUser } from '../services/auth';
import { fetchRideHistory } from '../services/rides';
const user=ref(null), rides=ref([]), loading=ref(true), error=ref(null);
onMounted(async()=>{user.value=await getStoredUser();try{rides.value=await fetchRideHistory()}catch(e){error.value=e.message}finally{loading.value=false}});
</script>
<template><MobileShell v-if="user" :role="user.role" :user-name="user.name"><main class="mobile-page history"><header><p class="mobile-eyebrow">Tus recorridos</p><h1 class="mobile-title">Carreras</h1></header><p v-if="loading" class="mobile-muted">Cargando carreras…</p><p v-else-if="error" class="mobile-alert">{{ error }}</p><section v-else-if="!rides.length" class="empty mobile-card"><span>🚕</span><h2>Aún no tienes carreras</h2><p>Cuando pidas tu primer viaje aparecerá aquí.</p><RouterLink class="mobile-button" :to="{name:'request-ride'}">Pedir una carrera</RouterLink></section><RouterLink v-for="ride in rides" :key="ride.id" class="ride mobile-card" :to="{name:'active-ride',params:{id:ride.id}}"><div class="ride-main"><div class="ride-state"><small>{{ ride.status_label || ride.status }}</small><em v-if="ride.needs_my_review">Calificar</em></div><strong>{{ ride.destination_address || 'Destino del viaje' }}</strong><span>Desde {{ ride.origin_address || 'tu ubicación' }}</span><p><b>${{ ride.price }}</b><i v-if="ride.distance_km">{{ ride.distance_km }} km</i></p></div><b class="arrow">›</b></RouterLink></main></MobileShell></template>
<style scoped>.history{display:grid;gap:1rem}.empty{padding:2rem 1.2rem;text-align:center}.empty>span{font-size:2rem}.empty h2{margin:.75rem 0 .3rem}.empty p{margin:0 0 1.2rem;color:var(--arka-muted);font-size:.85rem}.ride{padding:1rem;display:flex;justify-content:space-between;align-items:center;gap:.75rem;color:var(--arka-text);text-decoration:none}.ride-main{min-width:0;display:grid;gap:.25rem}.ride-state{display:flex;align-items:center;gap:.55rem}.ride small{color:var(--arka-primary);font-weight:800;text-transform:uppercase}.ride em{padding:.18rem .4rem;border-radius:999px;background:var(--arka-primary-soft);color:var(--arka-primary);font-size:.6rem;font-style:normal;font-weight:800}.ride strong,.ride span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ride span{color:var(--arka-muted);font-size:.75rem}.ride p{margin:.25rem 0 0;display:flex;gap:.75rem;color:var(--arka-text);font-size:.72rem}.ride p b{font-size:inherit}.ride p i{color:var(--arka-muted);font-style:normal}.ride .arrow{color:var(--arka-primary);font-size:1.4rem}</style>
